### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by justin97530** [andrewrk/mineflayer#168]
For some reason, with the new node-minecraft-protocol, my bot, and the examples, do not start. Instead they give this error:

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: null != null
    at createPacketBuffer (/Users/justin/Desktop/Bot/node_modules/minecraft-protocol/lib/protocol.js:1581:10)
    at Client.write (/Users/justin/Desktop/Bot/node_modules/minecraft-protocol/lib/client.js:112:16)
    at setSettings (/Users/justin/Desktop/Bot/lib/plugins/settings.js:27:16)
    at Client.<anonymous> (/Users/justin/Desktop/Bot/lib/plugins/settings.js:45:5)
    at Client.g (events.js:175:14)
    at Client.EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (/Users/justin/Desktop/Bot/node_modules/minecraft-protocol/lib/client.js:55:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
```

**Comment by roblabla** [comment]
Closing in favor of #198 for latest protocol support, #199 for multi-protocol support, and #193 for discussion about the status of the project.
