### ISSUE TITLE
/give results in a chat message that crashes when trying to parse it as json.

### ISSUE THREAD

**Issue by thejoshwolfe** [andrewrk/mineflayer#234]
```
Error parsing JSON Item Object [SyntaxError: Unexpected token m]

/home/josh/dev/mineflayer/lib/chat_message.js:129
				throw new Error('Expected JSON item object in hoverEvent.value');
				      ^
Error: Expected JSON item object in hoverEvent.value
    at ChatMessage.parse (/home/josh/dev/mineflayer/lib/chat_message.js:129:11)
    at new ChatMessage (/home/josh/dev/mineflayer/lib/chat_message.js:15:7)
    at /home/josh/dev/mineflayer/lib/chat_message.js:42:27
    at Array.forEach (native)
    at ChatMessage.parse (/home/josh/dev/mineflayer/lib/chat_message.js:37:14)
    at new ChatMessage (/home/josh/dev/mineflayer/lib/chat_message.js:15:7)
    at parseJsonMessage7 (/home/josh/dev/mineflayer/lib/plugins/chat.js:60:25)
    at parseJsonMessage (/home/josh/dev/mineflayer/lib/plugins/chat.js:88:9)
    at Client.<anonymous> (/home/josh/dev/mineflayer/lib/plugins/chat.js:102:5)
    at Client.emit (events.js:95:17)
```

**Comment by rom1504** [comment]
nice !
Not so nice of mojang to use json-but-not-actually-json...
