### ISSUE TITLE
Cannot read property 'id' of undefined at entities.js

### ISSUE THREAD

**Issue by AlexKvazos** [andrewrk/mineflayer#284]
https://github.com/andrewrk/mineflayer/blob/c8a3c621517b4a6fe1fce3d818c51aa76254bd67/lib/plugins/entities.js#L315

```
server-0 (err): TypeError: Cannot read property 'id' of undefined
server-0 (err):     at Client.<anonymous> (/home/MinecraftChat/node_modules/mineflayer/lib/plugins/entities.js:315:33)
server-0 (err):     at Client.emit (events.js:107:17)
server-0 (err):     at afterParse (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:97:10)
server-0 (err):     at parseNewStylePacket (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/protocol.js:1080:5)
server-0 (err):     at prepareParse (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:113:9)
server-0 (err):     at afterParse (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:101:5)
server-0 (err):     at parseNewStylePacket (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/protocol.js:1080:5)
server-0 (err):     at prepareParse (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:113:9)
server-0 (err):     at Socket.<anonymous> (/home/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:124:5)
server-0 (err):     at Socket.emit (events.js:107:17)
```

**Comment by rom1504** [comment]
When did this happen ?
Any way to reproduce it ?

**Comment by AlexKvazos** [comment]
I believe this happens when any of the enchantment or experience events are fired.

**Comment by AlexKvazos** [comment]
There was another stack trace before this one, let me go to my error logs and find it.
