### ISSUE TITLE
/invsee crashes the bot

### ISSUE THREAD

**Issue by AlexKvazos** [andrewrk/mineflayer#289]
When running /invsee <player> on a server, the following stack trace shows:

```
app1-6 (err): TypeError: undefined is not a function
app1-6 (err):     at Object.createWindow (/home/app1/node_modules/mineflayer/lib/windows.js:32:10)
app1-6 (err):     at Client.<anonymous> (/home/app1/node_modules/mineflayer/lib/plugins/inventory.js:394:33)
app1-6 (err):     at Client.emit (events.js:107:17)
app1-6 (err):     at afterParse (/home/app1/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:97:10)
app1-6 (err):     at parseNewStylePacket (/home/app1/node_modules/mineflayer/node_modules/minecraft-protocol/dist/protocol.js:1080:5)
app1-6 (err):     at prepareParse (/home/app1/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:113:9)
app1-6 (err):     at Socket.<anonymous> (/home/app1/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:124:5)
app1-6 (err):     at Socket.emit (events.js:107:17)
app1-6 (err):     at readableAddChunk (_stream_readable.js:163:16)
app1-6 (err):     at Socket.Readable.push (_stream_readable.js:126:10)
app1-6 (err):     at TCP.onread (net.js:538:20)
```

**Comment by rom1504** [comment]
Hmm what is /invsee ? Is there a server where I can test it ?

**Comment by AlexKvazos** [comment]
It is an essentials command given to staff members. You will have to run your own server, install essentials, op your self, and do `/invsee <playername>` to someone.

**Comment by AlexKvazos** [comment]
Thanks @Pietro210, nice job man!
