### ISSUE TITLE
Assertion error after /tp to nether

### ISSUE THREAD

**Issue by Darker** [andrewrk/mineflayer#306]
I teleported the bot into Nether using `/tp` command. This happened:

     assert.js:86
        throw new assert.AssertionError({
              ^
      AssertionError: 73984 === 61696
          at addColumn (C:\Users\Jakub\node_modules\mineflayer\lib\plugins\blocks.js:84:12)
          at Client.<anonymous> (C:\Users\Jakub\node_modules\mineflayer\lib\plugins\blocks.js:158:5)
          at Client.emit (events.js:107:17)
          at Deserializer.<anonymous> (C:\Users\Jakub\node_modules\minecraft-protocol\dist\client.js:149:12)
          at Deserializer.emit (events.js:107:17)
          at readableAddChunk (C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_readable.js:195:16)
          at Deserializer.Readable.push (C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_readable.js:162:10)
          at Deserializer.Transform.push (C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_transform.js:145:32)
          at Deserializer._transform (C:\Users\Jakub\node_modules\minecraft-protocol\dist\transforms\serializer.js:255:14)
          at Deserializer.Transform._read (C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_transform.js:184:10)
          at Deserializer.Transform._write (C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_transform.js:172:12)

This is why I don't use `assert` in production code (or any other honestly).

**Comment by rom1504** [comment]
Basically you are about the first one to try to put a mineflayer's bot in the Nether, so I'm not very surprised there are some problems.
This error means there are some info we are not reading in the block chunk. (and I think it's a good thing that it crashes here, since it means a mineflayer bug)

Can you reproduce it in a vanilla server ? (does it crash every time you tp in the nether ? or is it by teleporting it from the overworld to the nether ?)

**Comment by Darker** [comment]
Yeah, happens on vanilla too. Also, happens even if nether portal is used instead of `/tp` command.

**Comment by rom1504** [comment]
@Darker what `/tp` command are you using to teleport the bot to the nether ?
