### ISSUE TITLE
Some trouble with Debian

### ISSUE THREAD

**Issue by fuzzybow** [andrewrk/mineflayer#321]
Hey there! I was having a bit of trouble with instlaling this on Debian.

I used the NPM install, and then went to do a test, and got this:

\> mineflayer@1.3.0 test /home/matt/node_modules/mineflayer
\> mocha --reporter spec

module.js:338
    throw err;
          ^
Error: Cannot find module 'vec3'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/matt/node_modules/mineflayer/test/externalTest.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.

Any insight would be gladly appreciated.

**Comment by Gjum** [comment]
How did you install it with NPM? Can you post the command(s) you used?

**Comment by fuzzybow** [comment]
It was installed with NPM. just `npm install mineflayer`

**Comment by roblabla** [comment]
@fuzzybow did you create a project folder for your bot ? You seem to be very new to nodejs and/or npm. With NPM, deps aren't installed globally, unlike other languages like python. Instead, you first create a project (that is to say, a folder) and then, within that project, run `npm install mineflayer`.

Really, the command process to install mineflayer is something like : 

```
mkdir my_mineflayer_project
cd my_mineflayer_project
npm init
npm install --save mineflayer
```

then in that my_mineflayer_project folder, create a new js file and write your code using mineflayer in it :D

**Comment by rom1504** [comment]
If you have more issues with that, please reopen ;)
